Create JCB templates for marine B-matrix
NOAA-EMC/jcb-gdas pull request #36
Opened 2024-10-23 21:30 UTC by DavidNew-NOAA

This PR is a companion to Global Workflow PR [#2992](https://github.com/NOAA-EMC/global-workflow/pull/2992) and GDASApp PR ...

It adds JCB templates for the input YAMLS of JEDI applications used in the marine B-matrix task in the Global Workflow.

2024-10-24 13:20 UTC, danholdaway reviewed
Looks good. It might be good to modify the testing of marine in the main JCB repo to include these algorithms. There's an example of that for the atmosphere.

2024-10-24 13:54 UTC, guillaumevernieres reviewed
The 2 diffusion yamls are missing the "levels" key. I thought I modified in a previous prit but maybe not. I'll look into it later today.

2024-10-30 13:07 UTC, danholdaway approved these changes

2024-10-30 13:31 UTC, guillaumevernieres requested changes
Some updates are needed to the b-mat yaml, I'll look into it today.

2024-10-30 14:08 UTC, guillaumevernieres commented on algorithm/marine/soca_parameters_diffusion_vt.yaml.j2
> +          as gaussian: true
```suggestion
          as gaussian: true
          levels: '{{ marine_vt_levels }}'
```

2024-10-30 14:10 UTC, guillaumevernieres commented
Sorry for the late review @DavidNew-NOAA . I went through the yamls and it's only a one liner change.

2024-10-30 16:10 UTC, danholdaway commented on algorithm/marine/soca_parameters_diffusion_vt.yaml.j2
> +          as gaussian: true
This change would pass now.

2024-10-31 23:44 UTC, DavidNew-NOAA commented
> Looks good. It might be good to modify the testing of marine in the main JCB repo to include these algorithms. There's an example of that for the atmosphere.

@danholdaway Can you point me to where specifically? Is these testing changes necessary before this PR is merged?

2024-11-01 00:02 UTC, guillaumevernieres approved these changes

2024-11-01 14:18 UTC, danholdaway commented
I'll merge this and you can add to the testing later on. You would add to [this](https://github.com/NOAA-EMC/jcb-gdas/blob/develop/test/client_integration/gdas-marine-templates.yaml) file with something that looks like [this](https://github.com/NOAA-EMC/jcb-gdas/blob/1e9d844b0225acc2a0bf913358b1cd8581f9a2a9/test/client_integration/gdas-atmosphere-templates.yaml#L8).

2024-11-01 14:19 UTC, merged

2024-11-01 14:43 UTC, DavidNew-NOAA commented
Thanks @danholdaway